---
# tasks file for roles/database
# commentaire
- name: Run Database
  community.docker.docker_container:
    name: "{{db_name}}"
    pull: true
    recreate: true
    image: gregoryspn/tp1-database:latest
    networks:
      - name: app-network
    volumes:
      - /data
    env:
      POSTGRES_DB: "{{postgres_db}}"
      POSTGRES_USER: "{{postgres_user}}"
      POSTGRES_PASSWORD: "{{postgres_password}}"