---
# tasks file for roles/database
- name: Run Database
  community.docker.docker_container:
    name: database
    pull: true
    recreate: true
    image: gregoryspn/tp1-database:latest
    networks:
      - name: app-network
    volumes:
      - /data
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd