version: '3.8'

services:
  database:
    image: gregoryspn/tp1-database:1.0
    volumes:
      - ./Database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    networks:
      - app-network

  backend:
    image: gregoryspn/tp1-backend:1.0
    networks:
      - app-network
    environment:
      - DB_URL=jdbc:postgresql://database:5432/db
      - DB_USER=usr
      - DB_PASSWORD=pwd
    depends_on:
      - database

  httpd:
    image: gregoryspn/tp1-httpd:1.0
    ports:
      - 80:80
    networks:
      - app-network
    depends_on:
      - backend

  front:
    image: gregoryspn/myfront:1.0
    networks:
      - app-network
    depends_on:
      - backend

  
networks:
  app-network:
