---
# tasks file for roles/app
- name: Run App
  docker_container:
    name: backend
    image: gregoryspn/tp1-backend:1.0
    networks:
      - name: app-network
    env: 
      DB_URL: "jdbc:postgresql://database:5432/db" 
      DB_USER: "usr"
      DB_PASSWORD: "pwd"
