---
# tasks file for roles/proxy
- name: Run Proxy
  community.docker.docker_container:
    name: proxy
    pull: true
    recreate: true
    image: gregoryspn/tp1-httpd:latest
    networks:
      - name: app-network
    ports:
     - "80:80"