name: CI devops deploy 2024
on:
  workflow_run:
    workflows:
      - "CI devops docker 2024"
    types:
        - completed
    branches:
        - main

jobs:
  deploy_front: 
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          directory: ansible
          key: ${{secrets.SSH_KEY}}
          inventory: |
            [all]
            ${{ secrets.DEPLOY_HOST }}
          vault_password: ${{ secrets.VAULT_PASSWORD }}
          options: |
            -u centos