name: CI devops deploy 2024
on:
  workflow_run:
    workflows:
      - "CI devops docker 2024"
    types:
        - completed
    branches:
        - main

jobs:
  deploy_front: 
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-22.04
    steps:
      #checkout your github code using actions/checkout@v2.5.0
      - name: Checkout
        uses: actions/checkout@v2.5.0

     #run ansible playbook to deploy the backend.
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
            playbook: playbook.yml
            key: ${{secrets.SSH_PRIVATE_KEY}}
            directory: ansible
            inventory: |
              [all]
              gregory.spinar.takima.cloud
            vault_password: ${{secrets.VAULT_PASSWORD}}
            options: |
              -u centos